let exception$of({}->{})->{}->{}fun!x=(x();fn
y=>y)handle$z=>z val` =fn y=>raise$(fn z=> !z z)in! ` `end